require('ts-node/register/transpile-only');
const assert = require('assert');
const mock = require('mock-require');
const path = require('path');
const base = path.resolve(__dirname, '../../src');
const replace = (name, value) => mock(path.join(base, name), value);
const directory = '/Games/Valheim';
const profileRoot = '/Profiles/Two Words';
let missingLoader = false;
const calls = [];
replace('r2mm/manager/ManagerSettings.ts', { getSingleton: async () => ({ getContext: () => ({ gameSpecific: { launchParameters: '--name "Two Words"' } }) }) });
replace('providers/ror2/game/GameDirectoryResolverProvider.ts', { instance: { getDirectory: async () => directory } });
replace('providers/ror2/logging/LoggerProvider.ts', { instance: { Log: () => {} } });
replace('providers/generic/file/FsProvider.ts', { instance: { exists: async file => {
    if (file.endsWith('games.json')) return false;
    if (missingLoader && file.endsWith('libdoorstop_x64.dylib')) return false;
    return true;
} } });
replace('r2mm/launching/instructions/GameInstructions.ts', {});
replace('r2mm/launching/instructions/GameInstructionParser.ts', {});
const processUtils = require('../../src/utils/ProcessUtils');
replace('utils/ProcessUtils.ts', { ...processUtils, startProcess: async (...args) => calls.push(args) });
const Runner = require('../../src/r2mm/launching/runners/darwin/SteamGameRunner_Darwin').default;
(async () => {
    const runner = new Runner();
    const game = { displayName: 'Valheim', activePlatform: { storeIdentifier: '892970' } };
    const profile = { getProfileName: () => 'Two Words', getPathOfProfile: () => profileRoot };
    assert.equal(await runner.start(game, '', 'modded', profile), undefined);
    assert.equal(calls[0][0], '/usr/bin/arch');
    assert.equal(calls[0][1][0], '-x86_64');
    assert(calls[0][1].includes(`DYLD_INSERT_LIBRARIES=${profileRoot}/doorstop_libs/libdoorstop_x64.dylib`));
    assert(calls[0][1].includes(`DOORSTOP_TARGET_ASSEMBLY=${profileRoot}/BepInEx/core/BepInEx.Preloader.dll`));
    assert.equal(calls[0][1].at(-1), 'Two Words');
    assert.equal(await runner.start(game, '', 'vanilla', profile), undefined);
    assert.equal(calls[1][0], `${directory}/Valheim.app/Contents/MacOS/Valheim`);
    assert.deepEqual(calls[1][1], ['--name', 'Two Words']);
    missingLoader = true;
    const error = await runner.start(game, '', 'modded', profile);
    assert(error instanceof Error); assert.equal(calls.length, 2);
    console.log('PASS: Valheim Rosetta profile launch, vanilla direct launch, spaces, missing loader error');
})().catch(error => { console.error(error); process.exitCode = 1; });
